version: "3.9"

services:
  db:
    container_name: db
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: testdb
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - /var/lib/postgresql/data
    restart: always

  openbeats_611_pgadmin:
    container_name: openbeats_611_pgadmin
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@openbeats716.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "80:80"
      - "5050:5050"

  openbeats_611_api:
    container_name: openbeats_611_api
    build:
      dockerfile: Dockerfile
      context: ./api
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/testdb
    ports:
      - '5001:5001'

  openbeats_611_web:
    container_name: openbeats_611_web
    stdin_open: true
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      dockerfile: Dockerfile
      context: ./web
    volumes:
      - ./web:/app # live updates





